name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: 3.92.161.14
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "*"  # Specify the path to your app files
        target: "/var/www/html"  # Target directory on EC2

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.92.161.14 << 'EOF'
          cd /var/www/html # Change to the directory of your app
          git pull origin main  # Pull the latest changes
          # npm install           # Uncomment if you need to install dependencies
          # npm run build         # Uncomment if you need to build your app
          sudo systemctl restart nginx # Restart Nginx or your application
        EOF

