name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 400 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@34.229.239.147 << 'EOF'
        
          git config --global --add safe.directory /var/www/html

          sudo chown -R ubuntu:ubuntu /var/www/html

           
        # Navigate to the directory of your app
          cd /var/www/html 

          # Optional: If you are using git to manage your application, pull the latest changes
          git pull origin main 
 
          cat index.html

          sudo systemctl restart nginx 
        EOF

