name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: khalyomede/ssh-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
          # known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }} # Optional, add known hosts if needed

    - name: Deploy to EC2
      run: |
        ssh ubuntu@3.92.161.14 << 'EOF'
          cd /var/www/html/simple-todo-app # Change to the directory of your app
          git pull origin main  # Pull the latest changes
          # npm install           # Uncomment if you need to install dependencies
          # npm run build         # Uncomment if you need to build your app
          sudo systemctl restart nginx # Restart Nginx or your application
        EOF

